# Introduction {- #intro}

Apprendre la programmation ne devrait pas être une épreuve, mais plutôt un plaisir. Il est vrai qu'il existe beaucoup de style de programmation, de la programmation procédurale à la programmation logique en passant par la programmation orientée objet. Chacun peut avoir un avis sur le sujet mais peut importe le style choisie apprendre à programmer devrait être le plus simple possible pour ouvrir ce merveilleux monde au plus grand nombre.

C'est dans cette optique que j'ai accepté de refaire pour mon projet de mise en situation professionnel la bibliothèque graphique utilisé par l'IUT de Reims pour l'apprentissage de la programmation Orientée Objet (POO). Avec elle un débutant en programmation apprend en interagissant avec des entités visuelles ou tangibles via un programme préalablement écris par ce dernier. Le principe de la POO est de pouvoir manipuler dans son programme les concepts de la "vraie vie", étant donné que voir le résultat de ses travaux fait partie des meilleurs moyens d'apprentissage il est évident d'allier ces deux visions pour aboutir à un enseignement efficace. Ainsi avoir un ensemble de fonctions qui permettent de créer et manipuler des objets graphiques faciliterait grandement la tâche d'enseignement de la POO à de jeunes étudiants. C'est là l'objectif d'une bibliothèque, faciliter la réutilisation de d'un ensemble de fonctions pré-écrites et dans ce cas précis ce sera une bibliothèque orienté objets.

Cependant le développement d'une bibliothèque en générale fait intervenir différentes questions à ne pas prendre à la légère parmi les quelles on peut immédiatement citer la faisabilité ou du sujet selon le but de la bibliothèque, l'existence de bibliothèque faisant la même chose ou même l'utilisation finale de cette dernière. Par exemple il était jusqu'à la sortie de PHP 7.4 inimaginable de réaliser une bibliothèque graphique. En effet l'arrivé de l'extension FFI avec la nouvelle version de PHP a ouvert les possibilité du langage car elle emmène avec elle le moyen d'inclure des bibliothèque C directement en PHP sans avoir besoin de préalablement créer des extensions PHP en C, ce qui allège la courbe de développement en plus de permettre l'apport de nouvelles fonctionnalités au langage via ces bibliothèques.

Alors comment pouvons nous créer une bibliothèque PHP utilisant une autre bibliothèque C via FFI qui nous donnerais la possibilité de manipuler nos objets abstraits de programmation graphiquement ? C'est la question à la quelle j'ai essayé de répondre tout au long de ma mise en situation professionnelle.

Afin de traiter correctement ce sujet j'ai du établir un plan pour profiter au maximum des 4 semaines qui m'ont été données. Documentation, conception du projet, développement et distribution de celui-ci, sont les principales tâche que je me suis donné de terminer d'ici la fin de ces quatre semaines, et je vais les détailler dans ce mémoire.

Nous verrons dans un premier temps le contexte qui nous a amené à nous interroger sur la création d'une bibliothèque (I) \@ref(context), puis nous nous intéresserons au développement (II) \@ref(dev) et l'utilisation (III) \@ref(utils) de celle-ci avant de terminer par voir le résultat final de cette période de mise en situation professionnel et par conséquent l'aboutissement du développement de la bibliothèque (IV) \@ref(res).